import { MDXProvider } from '@mdx-js/react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MDXProvider components={{
        // Allows customizing built-in components, e.g. to add styling. DEMO:
        // 
        h1: ({ children }) => <h1 className='font-thin text-blue-600' >{children}</h1>,
      }}>
        <body className={inter.className}>{children}</body>
      </MDXProvider>
    </html>
  )
}
